#!/usr/bin/env node
/**
 * project-init — scaffold a project for the best AI-coding-agent experience.
 * Cross-tool: writes CLAUDE.md (Claude Code), AGENTS.md (Codex, Antigravity,
 * Cursor, opencode, Windsurf, ZAI Code (Kimi reads it too) — all read AGENTS.md
 * natively; the cross-tool standard), GEMINI.md (Antigravity-specific pointer),
 * and STATE.md (a session-continuity log). Auto-detects the stack and fills real build/test/lint
 * commands. No external dependencies.
 *
 * AGENTS.md is the single source of truth; CLAUDE.md and GEMINI.md are short
 * pointers to it — edit AGENTS.md once and every tool stays in sync.
 *
 * Usage:
 *   node project-init.js [dir] [--about "what the project is"] [--force]
 */
const fs = require("fs");
const path = require("path");
const { detectStack } = require(path.join(__dirname, "lib", "detect-stack.js"));

const ARGV = process.argv.slice(2);
const FORCE = ARGV.includes("--force");
const ABOUT = (() => { const i = ARGV.indexOf("--about"); return i >= 0 ? (ARGV[i + 1] || "") : ""; })();
// value-taking flags: their following token is a value, NOT the <dir> positional.
// Add any new "--flag <value>" here so its value isn't mis-read as the project dir.
const VALUE_FLAGS = new Set(["--about"]);
const dir = path.resolve(ARGV.find((a, i) => !a.startsWith("--") && !(i > 0 && VALUE_FLAGS.has(ARGV[i - 1]))) || process.cwd());

function isoDate() { const d = new Date(); const p = (n) => String(n).padStart(2, "0"); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`; }

function main() {
  const pname = path.basename(dir);
  const det = detectStack(dir);
  const stackList = [...new Set([...det.languages, ...det.frameworks])];
  const stack = stackList.length ? stackList.join(", ") : "(stack not recognized yet)";
  const cmdLines = Object.entries(det.commands).map(([k, v]) => `- **${k}:** \`${v}\``).join("\n")
    || "<!-- No commands detected; define real build/test/lint commands here -->";

  const foot = `\n\n---\nGenerated by project-init (${isoDate()}). Keep it concise (<150 lines) — bloated context hurts agent performance.`;
  const objetivo = ABOUT ? `\n## Goal\n${ABOUT}\n` : `\n## Goal\n<!-- What is this project and what are you trying to achieve? Fill this in — highest-value context. -->\n`;

  // Lean, best-practice (agents.md 2026): critical rules first, pair prohibitions
  // with alternatives, omit defaults the agent can infer, keep it short.
  const shared = `## Commands
${cmdLines}

## Structure (high level)
<!-- Key directories and their role. High level — the agent discovers files itself. -->

## Non-obvious patterns
<!-- Highest-signal section. Document ONLY the counterintuitive things (one real example > three paragraphs).
     Pair each prohibition with an alternative: "Don't instantiate X directly → use Y from lib/...". -->

## Permissions / boundaries
- Autonomous: read files, lint, run tests.
- Needs approval: install packages, commit/push, delete files, network or external actions.

## Conventions
- Follow existing patterns, helpers and style before introducing new ones.
- Handle errors explicitly; validate input at boundaries; no hardcoded secrets (use env / secret manager).
- Surgical changes; run the repo's checks and report real results.

## Commits / PR
- Conventional commits. Small, focused PRs with a test plan.

## Session continuity
- **"catchup"**: read \`STATE.md\` + \`git log --oneline -15\` + \`git status\`; summarize the last state and propose the next step. Don't change anything until confirmed.
- **"wrapup"**: update \`STATE.md\` fully (Done / In progress / Next / Decisions / Open threads), suggest a commit, confirm. Use before closing. (In Claude Code a Stop hook also writes a git snapshot.)`;

  const head = (h) => `# ${h}\n> **${pname}** · Stack: ${stack}\n${objetivo}`;

  const claudeMd = `# CLAUDE.md — ${pname}\n> 📌 **Full project context is in \`AGENTS.md\` — read it first** (goal, commands, structure, patterns, conventions, continuity). Single source of truth; don't duplicate here.${foot}`;
  const geminiMd = `# ${pname} — Antigravity\n> 📌 **Full context in \`AGENTS.md\` — read it.** Only Antigravity-specific overrides go here (they take priority over AGENTS.md).\n\n## Antigravity-specific\n<!-- Overrides/preferences only for Antigravity (planning style, browser/agent tools). Empty = inherit from AGENTS.md. -->${foot}`;
  const agentsMd = head(pname) + shared + foot;
  const aboutClean = ABOUT.replace(/\s*\.*\s*$/, "");   // strip trailing dots/space so we don't get ".."
  const stateMd = `# STATE — ${pname}\n> Continuity log. When you return, type **catchup** and the agent reads this + git to get up to speed.\n\n## Current state\nProject just initialized${aboutClean ? ": " + aboutClean : ""}.\n\n## Done\n-\n\n## In progress\n-\n\n## Next\n-\n\n## Decisions / key context\n-\n\n## Open threads / questions\n-\n\n---\nThe agent updates this at the end of each work block (or on "wrapup").\n`;

  const targets = [["AGENTS.md", agentsMd], ["CLAUDE.md", claudeMd], ["GEMINI.md", geminiMd], ["STATE.md", stateMd]];
  for (const [name, content] of targets) {
    const f = path.join(dir, name);
    if (fs.existsSync(f) && !FORCE) { console.log(`>> ${name} already exists (kept; --force to overwrite)`); continue; }
    fs.writeFileSync(f, content); console.log(`>> ${name} created`);
  }

  if (stackList.length) console.log(`>> Detected: ${stackList.join(", ")} | commands: ${Object.keys(det.commands).join(",") || "none"}`);
  if (det.isEmpty) console.log(`>> Stack not recognized — describe the project with --about, and consider discovering skills/agents for your stack online.`);
  console.log(`>> Ready for Claude Code + Codex + Antigravity + opencode + Cursor + Windsurf + ZAI Code (AGENTS.md is read by all, incl. Kimi; CLAUDE.md / GEMINI.md / STATE.md).`);
  if (ARGV.includes("--with-experts")) {
    const ids = (() => {
      try {
        const catalog = require(path.join(__dirname, "catalog", "catalog.json"));
        const { matchExperts } = require(path.join(__dirname, "lib", "match-experts.js"));
        return matchExperts(catalog, det, ABOUT).map(e => e.id);
      } catch { return []; }
    })();
    if (ids.length) {
      console.log(`>> Suggested experts for this stack: ${ids.join(", ")}`);
      console.log(`>> Preview:  node install-experts.js . --tools claude --experts ${ids.join(",")} --dry-run   # edit the tool list`);
      console.log(`>> Install:  add --yes after reviewing the preview.`);
    }
  }
  try {
    const mf = path.join(dir, ".aics-experts.json");
    if (fs.existsSync(mf)) {
      const man = JSON.parse(fs.readFileSync(mf, "utf8"));
      const n = (man.experts || []).length;
      if (n) {
        const srcs = [...new Set(man.experts.map(e => e.source))].join(", ");
        const oldest = man.experts.map(e => e.installedAt).filter(Boolean).sort()[0] || "?";
        console.log(`>> ${n} expert(s) installed from ${srcs} (since ${String(oldest).slice(0, 10)}). Refresh: node install-experts.js . --update --dry-run`);
      }
    }
  } catch { /* ignore */ }
}

if (require.main === module) main();
